export const card: string 
export const content: string
export const likes: string
export const info: string
export const post: string
export const replies: string
export const header: string
export const reply: string
export const avatar: string
export const userName: string
export const createdAt: string
export const score: string
export const plus: string
export const img__reply: string
export const button: string